# 1. From List to Arrays

In [1]:
# one dimensional list to arrays
# create one-dimensional array 
from numpy import array 
# list of data 
data = [11, 22, 33, 44, 55] 
# array of data 
data = array(data) 
print(data) 
print(type(data))


[11 22 33 44 55]
<class 'numpy.ndarray'>


In [2]:
# Two-Dimensional List of Lists to Array
# create two-dimensional array 
from numpy import array 
# list of data 
data = [[11, 22], 
        [33, 44], 
        [55, 66]] 
# array of data 
data = array(data) 
print(data) 
print(type(data))


[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


# 2. Array Indexing


In [3]:
# One-Dimensional Indexing
# index a one-dimensional array 
from numpy import array 
# define array 
data = array([11, 22, 33, 44, 55])
# index data 
print(data[0]) 
print(data[4])

11
55


In [4]:
# index array out of bounds 
from numpy import array 
# define array 
data = array([11, 22, 33, 44, 55]) 
# index data 
print(data[5])


IndexError: index 5 is out of bounds for axis 0 with size 5

In [5]:
# negative array indexing 
from numpy import array 
# define array 
data = array([11, 22, 33, 44, 55]) 
# index data 
print(data[-1]) 
print(data[-5])


55
11


In [7]:
# index two-dimensional array 
from numpy import array 
# define array 
data = array([ [11, 22], 
              [33, 44], 
              [55, 66]]) 
# index data 
print(data[0,0])


11


In [11]:
# Example of indexing the first row of a two-dimensional array.
# index row of two-dimensional array 
from numpy import array 
# define array
data = array([ [11, 22], [33, 44], [55, 66]]) 
# index data 
print(data[1,])


[33 44]


# 3. Array Slicing

In [12]:
# One-Dimensional Slicing
# slice a one-dimensional array 
from numpy import array 
# define array 
data = array([11, 22, 33, 44, 55])
print(data[:])


[11 22 33 44 55]


In [13]:
# slice a subset of a one-dimensional array 
from numpy import array
# define array 
data = array([11, 22, 33, 44, 55]) 
print(data[0:1])


[11]


In [14]:
# negative slicing of a one-dimensional array 
from numpy import array 
# define array 
data = array([11, 22, 33, 44, 55]) 
print(data[-2:])


[44 55]


In [15]:
# split input and output data 
from numpy import array 
# define array 
data = array([[11, 22, 33], 
              [44, 55, 66], 
              [77, 88, 99]]) 
# separate data 
X, y = data[:, :-1], data[:, -1] 
print(X) 
print(y)


[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [16]:
# split train and test data 
from numpy import array 
# define array 
data = array([ [11, 22, 33],
              [44, 55, 66], 
              [77, 88, 99]])
# separate data 
split = 2 
train,test = data[:split,:],data[split:,:] 
print(train) 
print(test)


[[11 22 33]
 [44 55 66]]
[[77 88 99]]


# 4. Array Reshaping

In [18]:
# shape of one-dimensional array 
from numpy import array 
# define array 
data = array([11, 22, 33, 44, 55]) 
print(data.shape)

(5,)


In [23]:
# shape of a two-dimensional array 
from numpy import array 
# list of data 
data = [[11, 22], [33, 44], [55, 66]] 
# array of data 
data = array(data) 
print(data.shape)


(3, 2)


In [20]:
# row and column shape of two-dimensional array 
from numpy import array 
# list of data 
data = [[11, 22],[33, 44], [55, 66]] 
# array of data 
data = array(data) 
print('Rows: %d' % data.shape[0]) 
print('Cols: %d' % data.shape[1])


Rows: 3
Cols: 2


In [28]:
# reshape 1D array to 2D 
from numpy import array 
# define array 
data = array([11, 22, 33, 44, 55]) 
print(data)
print(data.shape) 
# reshape 
data = data.reshape((data.shape[0], 1)) 
print(data.shape)

[11 22 33 44 55]
(5,)
(5, 1)


In [25]:
print(data)

[[11]
 [22]
 [33]
 [44]
 [55]]


In [29]:
# reshape 2D array to 3D 
from numpy import array 
# list of data 
data = [[11, 22], [33, 44], [55, 66]] 
print(data)
# array of data 
data = array(data) 
print(data.shape) 
# reshape 
data = data.reshape((data.shape[0], data.shape[1], 1)) 
print(data.shape)


[[11, 22], [33, 44], [55, 66]]
(3, 2)
(3, 2, 1)


In [27]:
print(data)

[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]
