In [16]:
# Limitation with Array
a = [1, 2, 3] 
print(a)
b = [1, 2, 3]
print(b)
c = a + b 
print(c)
c = [a[i] + b[i] for i in range(len(a))] 
print(c)

[1, 2, 3]
[1, 2, 3]
[1, 2, 3, 1, 2, 3]
[2, 4, 6]


In [15]:
c = [a[i] + b[i] for i in range(len(a))] 
print(c)

[2, 4, 6]


In [17]:
# broadcast scalar to one-dimensional array 
from numpy import array 
# define array 
a = array([1, 2, 3]) 
print(a) 
# define scalar 
b = 2 
print(b) 
# broadcast 
c = a + b 
print(c)

[1 2 3]
2
[3 4 5]


In [18]:
# broadcast scalar to two-dimensional array 
from numpy import array 
# define array 
A = array([ [1, 2, 3], [1, 2, 3]]) 
print(A)
# define scalar 
b = 2 
print(b) 
# broadcast 
C = A + b 
print(C)


[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


In [19]:
# broadcast one-dimensional array to two-dimensional array 
from numpy import array 
# define two-dimensional array 
A = array([ [1, 2, 3], [1, 2, 3]]) 
print(A) 
# define one-dimensional array 
b = array([1, 2, 3]) 
print(b) 
# broadcast 
C = A + b 
print(C)


[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]


In [21]:
# broadcasting error 
from numpy import array 
# define two-dimensional array
A = array([ [1, 2, 3], [1, 2, 3]]) 
print(A.shape) 
# define one-dimensional array 
b = array([1, 2]) 
print(b.shape) 
# attempt broadcast 
C = A + b 
print(C)


(2, 3)
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [22]:
#NO broadcasting error 
from numpy import array 
# define two-dimensional array
A = array([ [1, 2, 3], [1, 2, 3]]) 
print(A.shape) 
# define one-dimensional array 
b = array([1,]) 
print(b.shape) 
# attempt broadcast 
C = A + b 
print(C)

(2, 3)
(1,)
[[2 3 4]
 [2 3 4]]
